# ALI Automation - Project Creator (IntelliJ + Java 11)
# PowerShell Version

param(
    [Parameter(Position=0)]
    [string]$Command,
    
    [Parameter(Position=1)]
    [string]$ProjectName
)

$VERSION = "1.0.2"

function Show-Help {
    Write-Host "ALI Automation v$VERSION" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Usage: ali-automation create-project <PROJECT_NAME>"
    Write-Host ""
    Write-Host "Commands:" -ForegroundColor Yellow
    Write-Host "    create-project <name>    Create a new IntelliJ-ready Gradle project"
    Write-Host "    version                  Show version information"
    Write-Host "    help                     Show this help message"
    Write-Host ""
    Write-Host "Examples:" -ForegroundColor Yellow
    Write-Host "    ali-automation create-project MyTestProject"
    Write-Host "    ali-automation version"
    Write-Host "    ali-automation help"
}

function Show-Version {
    Write-Host "ALI Automation v$VERSION" -ForegroundColor Cyan
}

function Get-PackagePath {
    param([string]$projectName)
    
    Write-Host "📦 Enter the package name for your project (e.g., com.i2c.automation.icm):" -ForegroundColor Cyan
    $userPackage = Read-Host
    
    if ([string]::IsNullOrWhiteSpace($userPackage)) {
        Write-Host "⚠️  No package provided. Using default: com.i2c.automation.aliapp" -ForegroundColor Yellow
        $userPackage = "com.i2c.automation.aliapp"
    }
    
    $packagePath = $userPackage -replace '\.', '/'
    $packageName = $userPackage
    
    Write-Host "✅ Package set to: $packageName" -ForegroundColor Green
    Write-Host "📁 Source path: src/test/java/$packagePath/$projectName" -ForegroundColor Gray
    
    return @{
        PackagePath = $packagePath
        PackageName = $packageName
    }
}

function New-JavaFile {
    param(
        [string]$FilePath,
        [string]$PackageName,
        [string]$ProjectName,
        [string]$ProjectNameLower,
        [string]$SystemUserName,
        [string]$SystemUserEmail,
        [string]$GeneratedDate,
        [string]$Content
    )
    
    $header = @"
/**
 * This class was automatically generated by TestProject
 * Project: $ProjectName
 * Generated by: $SystemUserName ($SystemUserEmail)
 * Generated on $GeneratedDate.
 */
package $PackageName.$ProjectNameLower;

$Content
"@
    
    $header | Out-File -FilePath $FilePath -Encoding UTF8
}

function New-GradleProject {
    param([string]$projectName)
    
    if ([string]::IsNullOrWhiteSpace($projectName)) {
        Write-Host "❌ Usage: ali-automation create-project <ProjectName>" -ForegroundColor Red
        exit 1
    }
    
    $GRADLE_VERSION = "6.7"
    $WORK_DIR = Get-Location
    
    # Get package information
    $packageInfo = Get-PackagePath -projectName $projectName
    $PACKAGE_PATH = $packageInfo.PackagePath
    $PACKAGE_NAME = $packageInfo.PackageName
    
    $PROJECT_NAME = $projectName
    $PROJECT_NAME_LOWER = $projectName.ToLower()
    $ROOT_DIR = Join-Path $WORK_DIR $PROJECT_NAME
    $SRC_MAIN_DIR = Join-Path $ROOT_DIR "src\main\java\$PACKAGE_PATH"
    $SRC_TEST_DIR = Join-Path $ROOT_DIR "src\test\java\$PACKAGE_PATH\$PROJECT_NAME_LOWER"
    
    # Create directory structure
    Write-Host "🚀 Creating Gradle project '$PROJECT_NAME'..." -ForegroundColor Cyan
    New-Item -ItemType Directory -Force -Path $SRC_MAIN_DIR | Out-Null
    New-Item -ItemType Directory -Force -Path $SRC_TEST_DIR | Out-Null
    New-Item -ItemType Directory -Force -Path "$ROOT_DIR\src\main\resources" | Out-Null
    New-Item -ItemType Directory -Force -Path "$ROOT_DIR\src\test\resources" | Out-Null
    
    # Get system user info
    try {
        $SYSTEM_USER_NAME = git config user.name 2>$null
        if ([string]::IsNullOrWhiteSpace($SYSTEM_USER_NAME)) {
            $SYSTEM_USER_NAME = $env:USERNAME
        }
    } catch {
        $SYSTEM_USER_NAME = $env:USERNAME
    }
    
    try {
        $SYSTEM_USER_EMAIL = git config user.email 2>$null
        if ([string]::IsNullOrWhiteSpace($SYSTEM_USER_EMAIL)) {
            $SYSTEM_USER_EMAIL = "eng.st14@i2cinc.com"
        }
    } catch {
        $SYSTEM_USER_EMAIL = "eng.st14@i2cinc.com"
    }
    
    $GENERATED_DATE = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    
    # Create build.gradle
    $buildGradleContent = @'
plugins {
    id 'java'
    id 'maven'
    id 'io.qameta.allure' version '2.8.1'
}

group 'SampleProject.generated'
version '1.0'

sourceCompatibility = 11
targetCompatibility = 11

test {
    useJUnitPlatform()
}

repositories {
    mavenCentral()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}

jar {
    from sourceSets.test.output + sourceSets.test.allSource
    from { configurations.testRuntimeClasspath.collect { it.isDirectory() ? it : zipTree(it) } }
}

compileTestJava.options.compilerArgs.add '-parameters'

def allureVersion = "2.13.6"
def junit5Version = "5.6.2"
allure {
    autoconfigure = true
    aspectjweaver = true
    version = allureVersion
    clean = true
    useJUnit5 { version = allureVersion }
}
dependencies {
    testImplementation("io.qameta.allure:allure-java-commons:$allureVersion")
    testImplementation("org.junit.jupiter:junit-jupiter-api:$junit5Version")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:$junit5Version")
    testImplementation("org.junit.jupiter:junit-jupiter-params:$junit5Version")
    implementation group: 'commons-io', name: 'commons-io', version: '2.11.0'
    implementation group: 'com.ibm.informix', name: 'jdbc', version: '4.50.9'
    implementation group: 'org.json', name: 'json', version: '20220924'
    implementation group: 'org.apache.commons', name: 'commons-csv', version: '1.9.0'
    implementation group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '4.6.0'
}
'@
    
    $buildGradleContent | Out-File -FilePath "$ROOT_DIR\build.gradle" -Encoding UTF8
    
    # Create settings.gradle
    "rootProject.name = '$PROJECT_NAME'" | Out-File -FilePath "$ROOT_DIR\settings.gradle" -Encoding UTF8
    
    # Create main Java test file
    $mainClassContent = @"
import org.testng.Assert;
import io.qameta.allure.Allure;
import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVParser;
import org.apache.commons.csv.CSVRecord;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.FileReader;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;

public class $PROJECT_NAME {
    public static WebDriver driver;

    @BeforeAll
    static void setup() throws Exception {
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.addArguments("--remote-allow-origins=*", "ignore-certificate-errors");
        driver = new ChromeDriver(chromeOptions);
        driver.manage().timeouts().implicitlyWait(Duration.ofMillis(15000));
        driver.manage().window().maximize();
    }

    private static Object[][] provideParameters() throws Exception {
        List<${PROJECT_NAME}DataSource> csvList = new ArrayList<>();
        try (
            BufferedReader br = new BufferedReader(new FileReader("datasource/${PROJECT_NAME}_DataSource.csv"));
            CSVParser parser = CSVFormat.DEFAULT.withDelimiter(',').withHeader().parse(br);
        ) {
            for (CSVRecord record : parser) {
                ${PROJECT_NAME}DataSource csvObject = new ${PROJECT_NAME}DataSource();
                csvObject.TID = record.get("TC_ID");
                csvObject.Scenario_Description = record.get("Scenario_Description");
                csvObject.Application_URL = record.get("Application_URL");
                csvList.add(csvObject);
            }
            return csvList.stream()
                    .map(bean -> new Object[]{bean})
                    .toArray(Object[][]::new);
        }
    }

    @DisplayName("$PROJECT_NAME")
    @ParameterizedTest
    @MethodSource("provideParameters")
    void execute(${PROJECT_NAME}DataSource data) {
        try {
            // main logic
        } catch (Exception e) {
            data.Actual_Result = "Fail";
            Assert.fail("Fail: " + e.getMessage(), e);
        }
    }

    @AfterEach
    public void takeScreenShot() {
        Allure.attachment("Test End: ", new ByteArrayInputStream(((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES)));
    }

    @AfterAll
    static void tearDown() {
        if (driver != null) {
            driver.quit();
        }
    }
}
"@
    
    New-JavaFile -FilePath "$SRC_TEST_DIR\$PROJECT_NAME.java" `
        -PackageName $PACKAGE_NAME `
        -ProjectName $PROJECT_NAME `
        -ProjectNameLower $PROJECT_NAME_LOWER `
        -SystemUserName $SYSTEM_USER_NAME `
        -SystemUserEmail $SYSTEM_USER_EMAIL `
        -GeneratedDate $GENERATED_DATE `
        -Content $mainClassContent
    
    # Create DataSource class
    $dataSourceContent = @"
public class ${PROJECT_NAME}DataSource {

    String TID;
    String Scenario_Description;
    String Module_Name;
    String Application_URL;
    String Verify_Login;
    String LoggedIn_UserID;
    String LoggedIn_UserPassword;
    String OLD_Password;
    String New_Password;
    String Confirm_NewPassword;
    String Expected_Result;
    String Actual_Result;
    String Test_Result;

    @Override
    public String toString() {
        return "[" + TID + ',' + Module_Name + ',' + Scenario_Description + ']';
    }
}
"@
    
    New-JavaFile -FilePath "$SRC_TEST_DIR\${PROJECT_NAME}DataSource.java" `
        -PackageName $PACKAGE_NAME `
        -ProjectName $PROJECT_NAME `
        -ProjectNameLower $PROJECT_NAME_LOWER `
        -SystemUserName $SYSTEM_USER_NAME `
        -SystemUserEmail $SYSTEM_USER_EMAIL `
        -GeneratedDate $GENERATED_DATE `
        -Content $dataSourceContent
    
    # Create Screen class
    $screenContent = @"
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

public class ${PROJECT_NAME}Screen {
    String oldPasswordFieldId = "old-password";
    String newPasswordFieldId = "new-password";
    String confirmNewPasswordFieldId = "confirm-password";
    String submitButtonId = "continueButton";

    private ${PROJECT_NAME}Screen() {}

    private static ${PROJECT_NAME}Screen instance = null;

    public static ${PROJECT_NAME}Screen getInstance() {
        if (instance == null) {
            instance = new ${PROJECT_NAME}Screen();
        }
        return instance;
    }

    public void execute(WebDriver driver, ${PROJECT_NAME}DataSource data) {
       driver.findElement(By.id(oldPasswordFieldId)).sendKeys(data.OLD_Password);
       driver.findElement(By.id(newPasswordFieldId)).sendKeys(data.New_Password);
       driver.findElement(By.id(confirmNewPasswordFieldId)).sendKeys(data.Confirm_NewPassword);
       driver.findElement(By.id(submitButtonId)).click();
    }
}
"@
    
    New-JavaFile -FilePath "$SRC_TEST_DIR\${PROJECT_NAME}Screen.java" `
        -PackageName $PACKAGE_NAME `
        -ProjectName $PROJECT_NAME `
        -ProjectNameLower $PROJECT_NAME_LOWER `
        -SystemUserName $SYSTEM_USER_NAME `
        -SystemUserEmail $SYSTEM_USER_EMAIL `
        -GeneratedDate $GENERATED_DATE `
        -Content $screenContent
    
    # Create Navigation class
    $navigationContent = @"
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

public class Navigation {
    private static String User_Info_Button_Id = "user-info-drop";
    public static void selectUserInfoButton(WebDriver driver) throws Exception {
        By by = By.id(User_Info_Button_Id);
        driver.findElement(by).click();
        Thread.sleep(2000);
    }
}
"@
    
    New-JavaFile -FilePath "$SRC_TEST_DIR\Navigation.java" `
        -PackageName $PACKAGE_NAME `
        -ProjectName $PROJECT_NAME `
        -ProjectNameLower $PROJECT_NAME_LOWER `
        -SystemUserName $SYSTEM_USER_NAME `
        -SystemUserEmail $SYSTEM_USER_EMAIL `
        -GeneratedDate $GENERATED_DATE `
        -Content $navigationContent
    
    # Create supporting folders and files
    New-Item -ItemType Directory -Force -Path "$ROOT_DIR\cleanup" | Out-Null
    New-Item -ItemType Directory -Force -Path "$ROOT_DIR\datasource" | Out-Null
    "-- SQL cleanup script for $PROJECT_NAME" | Out-File -FilePath "$ROOT_DIR\cleanup\${PROJECT_NAME}_CleanUp.sql" -Encoding UTF8
    "TC_ID,Scenario_Description,Application_URL" | Out-File -FilePath "$ROOT_DIR\datasource\${PROJECT_NAME}_DataSource.csv" -Encoding UTF8
    
    # Check Java 11
    Write-Host "🧩 Checking Java 11 environment..." -ForegroundColor Cyan
    try {
        $javaVersion = java -version 2>&1 | Select-String "version"
        if ($javaVersion -match '"11\.') {
            Write-Host "✅ Java 11 detected: $javaVersion" -ForegroundColor Green
        } else {
            Write-Host "⚠️  Java 11 not detected. Please install Java 11 using:" -ForegroundColor Yellow
            Write-Host "   scoop install java/openjdk11" -ForegroundColor Yellow
            Write-Host "   or" -ForegroundColor Yellow
            Write-Host "   scoop install java/temurin11-jdk" -ForegroundColor Yellow
        }
    } catch {
        Write-Host "⚠️  Java not found. Please install Java 11." -ForegroundColor Yellow
    }
    
    # Setup Gradle wrapper
    Push-Location $ROOT_DIR
    Write-Host "🛠  Setting up Gradle wrapper version $GRADLE_VERSION..." -ForegroundColor Cyan
    New-Item -ItemType Directory -Force -Path "gradle\wrapper" | Out-Null
    "distributionUrl=https\://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip" | 
        Out-File -FilePath "gradle\wrapper\gradle-wrapper.properties" -Encoding UTF8
    
    # Check for Gradle
    if (Get-Command gradle -ErrorAction SilentlyContinue) {
        gradle wrapper --gradle-version $GRADLE_VERSION
    } else {
        Write-Host "⚠️  Gradle not found. Please install using: scoop install gradle" -ForegroundColor Yellow
        Write-Host "   You can run 'gradle wrapper' manually after installation." -ForegroundColor Yellow
    }
    
    # Create IntelliJ module file
    Write-Host "🧩 Creating IntelliJ module file..." -ForegroundColor Cyan
    $imlContent = @"
<?xml version="1.0" encoding="UTF-8"?>
<module type="JAVA_MODULE" version="4">
  <component name="NewModuleRootManager">
    <output url="file://`$MODULE_DIR`$/build/classes/java/main" />
    <output-test url="file://`$MODULE_DIR`$/build/classes/java/test" />
    <content url="file://`$MODULE_DIR`$">
      <sourceFolder url="file://`$MODULE_DIR`$/src/main/java" isTestSource="false" />
      <sourceFolder url="file://`$MODULE_DIR`$/src/test/java" isTestSource="true" />
      <excludeFolder url="file://`$MODULE_DIR`$/build" />
      <excludeFolder url="file://`$MODULE_DIR`$/.gradle" />
    </content>
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
  </component>
</module>
"@
    
    $imlContent | Out-File -FilePath "$ROOT_DIR\$PROJECT_NAME.iml" -Encoding UTF8
    
    Pop-Location
    
    Write-Host ""
    Write-Host "✅ Project '$PROJECT_NAME' created successfully!" -ForegroundColor Green
    Write-Host "📁 Location: $ROOT_DIR" -ForegroundColor Cyan
    Write-Host "📦 Package: $PACKAGE_NAME.$PROJECT_NAME_LOWER" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "📌 Next steps:" -ForegroundColor Yellow
    Write-Host "   1. Open the project in IntelliJ IDEA"
    Write-Host "   2. Ensure Java 11 SDK is configured"
    Write-Host "   3. Run '.\gradlew build' to verify setup"
}

# Main execution
switch ($Command) {
    "create-project" {
        if ([string]::IsNullOrWhiteSpace($ProjectName)) {
            Write-Host "❌ Project name is required" -ForegroundColor Red
            exit 1
        }
        New-GradleProject -projectName $ProjectName
    }
    "version" {
        Show-Version
    }
    "help" {
        Show-Help
    }
    "" {
        Show-Help
    }
    default {
        Show-Help
    }
}
