@echo off
setlocal enabledelayedexpansion

REM ALI Automation - Project Creator (IntelliJ + Java 11)
set VERSION=1.0.2

if "%~1"=="" goto :show_help
if /i "%~1"=="create-project" goto :create_project
if /i "%~1"=="version" goto :show_version
if /i "%~1"=="help" goto :show_help
if /i "%~1"=="--help" goto :show_help
if /i "%~1"=="-h" goto :show_help
goto :show_help

:show_help
echo ALI Automation v%VERSION%
echo.
echo Usage: ali-automation create-project ^<PROJECT_NAME^>
echo.
echo Commands:
echo     create-project ^<name^>    Create a new IntelliJ-ready Gradle project
echo     version                  Show version information
echo     help                     Show this help message
echo.
echo Examples:
echo     ali-automation create-project MyTestProject
echo     ali-automation version
echo     ali-automation help
goto :eof

:show_version
echo ALI Automation v%VERSION%
goto :eof

:create_project
if "%~2"=="" (
    echo ❌ Project name is required
    exit /b 1
)
set PROJECT_NAME=%~2
set GRADLE_VERSION=6.7
set WORK_DIR=%CD%

REM Get package path from user
echo 📦 Enter the package name for your project (e.g., com.i2c.automation.icm):
set /p user_package=
if "!user_package!"=="" (
    echo ⚠️  No package provided. Using default: com.i2c.automation.aliapp
    set user_package=com.i2c.automation.aliapp
)

REM Convert dots to slashes for directory path
set PACKAGE_PATH=!user_package:.=/!
set PACKAGE_NAME=!user_package!

echo ✅ Package set to: !PACKAGE_NAME!

REM Convert project name to lowercase
set PROJECT_NAME_LOWER=%PROJECT_NAME%
for %%L in (A B C D E F G H I J K L M N O P Q R S T U V W X Y Z) do (
    set PROJECT_NAME_LOWER=!PROJECT_NAME_LOWER:%%L=%%L!
)
call :tolower PROJECT_NAME_LOWER

set ROOT_DIR=%WORK_DIR%\%PROJECT_NAME%
set SRC_MAIN_DIR=%ROOT_DIR%\src\main\java\%PACKAGE_PATH%
set SRC_TEST_DIR=%ROOT_DIR%\src\test\java\%PACKAGE_PATH%\%PROJECT_NAME_LOWER%

REM Create directory structure
echo 🚀 Creating Gradle project '%PROJECT_NAME%'...
mkdir "%SRC_MAIN_DIR%" 2>nul
mkdir "%SRC_TEST_DIR%" 2>nul
mkdir "%ROOT_DIR%\src\main\resources" 2>nul
mkdir "%ROOT_DIR%\src\test\resources" 2>nul

REM Get system user info
for /f "tokens=*" %%i in ('git config user.name 2^>nul') do set SYSTEM_USER_NAME=%%i
if "!SYSTEM_USER_NAME!"=="" set SYSTEM_USER_NAME=%USERNAME%
for /f "tokens=*" %%i in ('git config user.email 2^>nul') do set SYSTEM_USER_EMAIL=%%i
if "!SYSTEM_USER_EMAIL!"=="" set SYSTEM_USER_EMAIL=eng.st14@i2cinc.com
set GENERATED_DATE=%date% %time%

REM Create build.gradle
(
echo plugins {
echo     id 'java'
echo     id 'maven'
echo     id 'io.qameta.allure' version '2.8.1'
echo }
echo.
echo group 'SampleProject.generated'
echo version '1.0'
echo.
echo sourceCompatibility = 11
echo targetCompatibility = 11
echo.
echo test {
echo     useJUnitPlatform^(^)
echo }
echo.
echo repositories {
echo     mavenCentral^(^)
echo     maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
echo }
echo.
echo jar {
echo     from sourceSets.test.output + sourceSets.test.allSource
echo     from { configurations.testRuntimeClasspath.collect { it.isDirectory^(^) ? it : zipTree^(it^) } }
echo }
echo.
echo compileTestJava.options.compilerArgs.add '-parameters'
echo.
echo def allureVersion = "2.13.6"
echo def junit5Version = "5.6.2"
echo allure {
echo     autoconfigure = true
echo     aspectjweaver = true
echo     version = allureVersion
echo     clean = true
echo     useJUnit5 { version = allureVersion }
echo }
echo dependencies {
echo     testImplementation^("io.qameta.allure:allure-java-commons:$allureVersion"^)
echo     testImplementation^("org.junit.jupiter:junit-jupiter-api:$junit5Version"^)
echo     testImplementation^("org.junit.jupiter:junit-jupiter-engine:$junit5Version"^)
echo     testImplementation^("org.junit.jupiter:junit-jupiter-params:$junit5Version"^)
echo     implementation group: 'commons-io', name: 'commons-io', version: '2.11.0'
echo     implementation group: 'com.ibm.informix', name: 'jdbc', version: '4.50.9'
echo     implementation group: 'org.json', name: 'json', version: '20220924'
echo     implementation group: 'org.apache.commons', name: 'commons-csv', version: '1.9.0'
echo     implementation group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '4.6.0'
echo }
) > "%ROOT_DIR%\build.gradle"

REM Create settings.gradle
echo rootProject.name = '%PROJECT_NAME%' > "%ROOT_DIR%\settings.gradle"

REM Create main Java file
(
echo /**
echo  * This class was automatically generated by TestProject
echo  * Project: %PROJECT_NAME%
echo  * Generated by: !SYSTEM_USER_NAME! ^(!SYSTEM_USER_EMAIL!^)
echo  * Generated on !GENERATED_DATE!.
echo  */
echo package !PACKAGE_NAME!.%PROJECT_NAME_LOWER%;
echo.
echo import org.testng.Assert;
echo import io.qameta.allure.Allure;
echo import org.apache.commons.csv.CSVFormat;
echo import org.apache.commons.csv.CSVParser;
echo import org.apache.commons.csv.CSVRecord;
echo import org.junit.jupiter.api.AfterAll;
echo import org.junit.jupiter.api.AfterEach;
echo import org.junit.jupiter.api.BeforeAll;
echo import org.junit.jupiter.api.DisplayName;
echo import org.junit.jupiter.params.ParameterizedTest;
echo import org.junit.jupiter.params.provider.MethodSource;
echo import org.openqa.selenium.OutputType;
echo import org.openqa.selenium.TakesScreenshot;
echo import org.openqa.selenium.WebDriver;
echo import org.openqa.selenium.chrome.ChromeDriver;
echo import org.openqa.selenium.chrome.ChromeOptions;
echo.
echo import java.io.BufferedReader;
echo import java.io.ByteArrayInputStream;
echo import java.io.FileReader;
echo import java.time.Duration;
echo import java.util.ArrayList;
echo import java.util.List;
echo.
echo public class %PROJECT_NAME% {
echo     public static WebDriver driver;
echo.
echo     @BeforeAll
echo     static void setup^(^) throws Exception {
echo         ChromeOptions chromeOptions = new ChromeOptions^(^);
echo         chromeOptions.addArguments^("--remote-allow-origins=*", "ignore-certificate-errors"^);
echo         driver = new ChromeDriver^(chromeOptions^);
echo         driver.manage^(^).timeouts^(^).implicitlyWait^(Duration.ofMillis^(15000^)^);
echo         driver.manage^(^).window^(^).maximize^(^);
echo     }
echo.
echo     private static Object[][] provideParameters^(^) throws Exception {
echo         List^<%PROJECT_NAME%DataSource^> csvList = new ArrayList^<^>^(^);
echo         try ^(
echo             BufferedReader br = new BufferedReader^(new FileReader^("datasource/%PROJECT_NAME%_DataSource.csv"^)^);
echo             CSVParser parser = CSVFormat.DEFAULT.withDelimiter^(','^^).withHeader^(^).parse^(br^);
echo         ^) {
echo             for ^(CSVRecord record : parser^) {
echo                 %PROJECT_NAME%DataSource csvObject = new %PROJECT_NAME%DataSource^(^);
echo                 csvObject.TID = record.get^("TC_ID"^);
echo                 csvObject.Scenario_Description = record.get^("Scenario_Description"^);
echo                 csvObject.Application_URL = record.get^("Application_URL"^);
echo                 csvList.add^(csvObject^);
echo             }
echo             return csvList.stream^(^)
echo                     .map^(bean -^> new Object[]{bean}^)
echo                     .toArray^(Object[][]::new^);
echo         }
echo     }
echo.
echo     @DisplayName^("%PROJECT_NAME%"^)
echo     @ParameterizedTest
echo     @MethodSource^("provideParameters"^)
echo     void execute^(%PROJECT_NAME%DataSource data^) {
echo         try {
echo             // main logic
echo         } catch ^(Exception e^) {
echo             data.Actual_Result = "Fail";
echo             Assert.fail^("Fail: " + e.getMessage^(^), e^);
echo         }
echo     }
echo.
echo     @AfterEach
echo     public void takeScreenShot^(^) {
echo         Allure.attachment^("Test End: ", new ByteArrayInputStream^(^(^(TakesScreenshot^) driver^).getScreenshotAs^(OutputType.BYTES^)^)^);
echo     }
echo.
echo     @AfterAll
echo     static void tearDown^(^) {
echo         if ^(driver != null^) {
echo             driver.quit^(^);
echo         }
echo     }
echo }
) > "%SRC_TEST_DIR%\%PROJECT_NAME%.java"

REM Create DataSource Java file
(
echo /**
echo  * This class was automatically generated by TestProject
echo  * Project: %PROJECT_NAME%
echo  * Generated by: !SYSTEM_USER_NAME! ^(!SYSTEM_USER_EMAIL!^)
echo  * Generated on !GENERATED_DATE!.
echo  */
echo package !PACKAGE_NAME!.%PROJECT_NAME_LOWER%;
echo.
echo public class %PROJECT_NAME%DataSource {
echo.
echo     String TID;
echo     String Scenario_Description;
echo     String Module_Name;
echo     String Application_URL;
echo     String Verify_Login;
echo     String LoggedIn_UserID;
echo     String LoggedIn_UserPassword;
echo     String OLD_Password;
echo     String New_Password;
echo     String Confirm_NewPassword;
echo     String Expected_Result;
echo     String Actual_Result;
echo     String Test_Result;
echo.
echo     @Override
echo     public String toString^(^) {
echo         return "[" + TID + ',' + Module_Name + ',' + Scenario_Description + ']';
echo     }
echo }
) > "%SRC_TEST_DIR%\%PROJECT_NAME%DataSource.java"

REM Create Screen Java file
(
echo /**
echo  * This class was automatically generated by TestProject
echo  * Project: %PROJECT_NAME%
echo  * Generated by: !SYSTEM_USER_NAME! ^(!SYSTEM_USER_EMAIL!^)
echo  * Generated on !GENERATED_DATE!.
echo  */
echo package !PACKAGE_NAME!.%PROJECT_NAME_LOWER%;
echo.
echo import org.openqa.selenium.By;
echo import org.openqa.selenium.WebDriver;
echo.
echo public class %PROJECT_NAME%Screen {
echo     String oldPasswordFieldId = "old-password";
echo     String newPasswordFieldId = "new-password";
echo     String confirmNewPasswordFieldId = "confirm-password";
echo     String submitButtonId = "continueButton";
echo.
echo     private %PROJECT_NAME%Screen^(^) {}
echo.
echo     private static %PROJECT_NAME%Screen instance = null;
echo.
echo     public static %PROJECT_NAME%Screen getInstance^(^) {
echo         if ^(instance == null^) {
echo             instance = new %PROJECT_NAME%Screen^(^);
echo         }
echo         return instance;
echo     }
echo.
echo     public void execute^(WebDriver driver, %PROJECT_NAME%DataSource data^) {
echo        driver.findElement^(By.id^(oldPasswordFieldId^)^).sendKeys^(data.OLD_Password^);
echo        driver.findElement^(By.id^(newPasswordFieldId^)^).sendKeys^(data.New_Password^);
echo        driver.findElement^(By.id^(confirmNewPasswordFieldId^)^).sendKeys^(data.Confirm_NewPassword^);
echo        driver.findElement^(By.id^(submitButtonId^)^).click^(^);
echo     }
echo }
) > "%SRC_TEST_DIR%\%PROJECT_NAME%Screen.java"

REM Create Navigation Java file
(
echo /**
echo  * This class was automatically generated by TestProject
echo  * Project: %PROJECT_NAME%
echo  * Generated by: !SYSTEM_USER_NAME! ^(!SYSTEM_USER_EMAIL!^)
echo  * Generated on !GENERATED_DATE!.
echo  */
echo package !PACKAGE_NAME!.%PROJECT_NAME_LOWER%;
echo.
echo import org.openqa.selenium.By;
echo import org.openqa.selenium.WebDriver;
echo.
echo public class Navigation {
echo     private static String User_Info_Button_Id = "user-info-drop";
echo     public static void selectUserInfoButton^(WebDriver driver^) throws Exception {
echo         By by = By.id^(User_Info_Button_Id^);
echo         driver.findElement^(by^).click^(^);
echo         Thread.sleep^(2000^);
echo     }
echo }
) > "%SRC_TEST_DIR%\Navigation.java"

REM Create supporting folders and files
mkdir "%ROOT_DIR%\cleanup" 2>nul
mkdir "%ROOT_DIR%\datasource" 2>nul
echo -- SQL cleanup script for %PROJECT_NAME% > "%ROOT_DIR%\cleanup\%PROJECT_NAME%_CleanUp.sql"
echo TC_ID,Scenario_Description,Application_URL > "%ROOT_DIR%\datasource\%PROJECT_NAME%_DataSource.csv"

REM Check for Java 11
echo 🧩 Checking Java 11 environment...
java -version 2>&1 | findstr /r "\"11\." >nul
if errorlevel 1 (
    echo ⚠️  Java 11 not detected. Please install Java 11 using:
    echo    scoop install java/openjdk11
    echo    or
    echo    scoop install java/temurin11-jdk
) else (
    java -version 2>&1 | findstr "version" | more
)

REM Setup Gradle wrapper
cd "%ROOT_DIR%"
echo 🛠  Setting up Gradle wrapper version %GRADLE_VERSION%...
mkdir gradle\wrapper 2>nul
(
echo distributionUrl=https\://services.gradle.org/distributions/gradle-%GRADLE_VERSION%-bin.zip
) > gradle\wrapper\gradle-wrapper.properties

REM Check if gradle is available
where gradle >nul 2>nul
if errorlevel 1 (
    echo ⚠️  Gradle not found. Please install using: scoop install gradle
    echo    You can run 'gradle wrapper' manually after installation.
) else (
    call gradle wrapper --gradle-version %GRADLE_VERSION%
)

REM Create IntelliJ module file
echo 🧩 Creating IntelliJ module file...
(
echo ^<?xml version="1.0" encoding="UTF-8"?^>
echo ^<module type="JAVA_MODULE" version="4"^>
echo   ^<component name="NewModuleRootManager"^>
echo     ^<output url="file://$MODULE_DIR$/build/classes/java/main" /^>
echo     ^<output-test url="file://$MODULE_DIR$/build/classes/java/test" /^>
echo     ^<content url="file://$MODULE_DIR$"^>
echo       ^<sourceFolder url="file://$MODULE_DIR$/src/main/java" isTestSource="false" /^>
echo       ^<sourceFolder url="file://$MODULE_DIR$/src/test/java" isTestSource="true" /^>
echo       ^<excludeFolder url="file://$MODULE_DIR$/build" /^>
echo       ^<excludeFolder url="file://$MODULE_DIR$/.gradle" /^>
echo     ^</content^>
echo     ^<orderEntry type="inheritedJdk" /^>
echo     ^<orderEntry type="sourceFolder" forTests="false" /^>
echo   ^</component^>
echo ^</module^>
) > "%ROOT_DIR%\%PROJECT_NAME%.iml"

cd "%WORK_DIR%"
echo ✅ Project '%PROJECT_NAME%' created successfully!
echo 📁 Location: %ROOT_DIR%
echo 📦 Package: !PACKAGE_NAME!.%PROJECT_NAME_LOWER%
echo.
echo 📌 Next steps:
echo    1. Open the project in IntelliJ IDEA
echo    2. Ensure Java 11 SDK is configured
echo    3. Run 'gradlew build' to verify setup

goto :eof

:tolower
REM Convert variable to lowercase
set %~1=!%1:A=a!
set %~1=!%1:B=b!
set %~1=!%1:C=c!
set %~1=!%1:D=d!
set %~1=!%1:E=e!
set %~1=!%1:F=f!
set %~1=!%1:G=g!
set %~1=!%1:H=h!
set %~1=!%1:I=i!
set %~1=!%1:J=j!
set %~1=!%1:K=k!
set %~1=!%1:L=l!
set %~1=!%1:M=m!
set %~1=!%1:N=n!
set %~1=!%1:O=o!
set %~1=!%1:P=p!
set %~1=!%1:Q=q!
set %~1=!%1:R=r!
set %~1=!%1:S=s!
set %~1=!%1:T=t!
set %~1=!%1:U=u!
set %~1=!%1:V=v!
set %~1=!%1:W=w!
set %~1=!%1:X=x!
set %~1=!%1:Y=y!
set %~1=!%1:Z=z!
goto :eof

:eof
endlocal
